export dedupe from './dedupe'
export every from './every'
export forEach from './forEach'
export groupBy from './groupBy'
export partition from './partition'
export reduce from './reduce'
export some from './some'
